name: Java CI-CD with Gradle

on:
  push:
    tags:
      - '*alpha*'

jobs:
  build:
    #	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: "Set up JDK 21"
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle
      - name: "Build with Gradle"
        run: |
          ./gradlew clean
          ./gradlew shadowJar -PBuildFull=false
          ./gradlew shadowJar -PBuildFull=true
      - name: "Stage"
        run: |
          mkdir -p staging
          mv build/libs/*.jar staging/
      - name: "Build & test"
        run: |
          TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "done!"
      - name: "GitHub Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.build.outputs.TAG }}"
          prerelease: true
          files: |
            staging/*.jar
